version: 2

sources:
  - name: stackoverflow
    database: stack-overflow-340613
    tables:
      - name: badges
      - name: comments
      - name: post_links
      - name: post_answers
      - name: post_history
      - name: posts_moderator_nomination
      - name: posts_orphaned_tag_wiki
      - name: posts_privilege_wiki
      - name: posts_questions
      - name: posts_tag_wiki
      - name: posts_tag_wiki_excerpt
      - name: posts_wiki_placeholder
      - name: stackoverflow_posts
      - name: tags
      - name: users
      - name: votes
    